version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tms
    volumes:
      - ./database_sql/tms.sql:/docker-entrypoint-initdb.d/tms.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./tms_be
      dockerfile: Dockerfile.backend
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tms?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "ping", "-c", "1", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./tms_fe
      dockerfile: Dockerfile.frontend
    container_name: frontend
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5