version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-DB
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tms
    volumes:
      - ./database_sql/tms.sql:/docker-entrypoint-initdb.d/tms.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.backend
  #   container_name: backend
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/your_database
  #     - SPRING_DATASOURCE_USERNAME=root
  #     - SPRING_DATASOURCE_PASSWORD=your_password
  #   ports:
  #     - "8080:8080"
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   container_name: frontend
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   ports:
  #     - "80:80"
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
